export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "22dd74f7": [() => import(/* webpackChunkName: "22dd74f7" */ "@generated/docusaurus-plugin-content-docs/default/p/index-466.json"), "@generated/docusaurus-plugin-content-docs/default/p/index-466.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/index-466.json")],
  "24ce2b44": [() => import(/* webpackChunkName: "24ce2b44" */ "@site/docs/overview/how-we-differ.md"), "@site/docs/overview/how-we-differ.md", require.resolveWeak("@site/docs/overview/how-we-differ.md")],
  "40df022e": [() => import(/* webpackChunkName: "40df022e" */ "@site/docs/use-cases/crosschain-liquidity.md"), "@site/docs/use-cases/crosschain-liquidity.md", require.resolveWeak("@site/docs/use-cases/crosschain-liquidity.md")],
  "562cc2a2": [() => import(/* webpackChunkName: "562cc2a2" */ "@site/docs/protocol/call-abstraction.md"), "@site/docs/protocol/call-abstraction.md", require.resolveWeak("@site/docs/protocol/call-abstraction.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "66793260": [() => import(/* webpackChunkName: "66793260" */ "@site/docs/use-cases/bridging.md"), "@site/docs/use-cases/bridging.md", require.resolveWeak("@site/docs/use-cases/bridging.md")],
  "7dadde4a": [() => import(/* webpackChunkName: "7dadde4a" */ "@site/docs/protocol/glossary.md"), "@site/docs/protocol/glossary.md", require.resolveWeak("@site/docs/protocol/glossary.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a864fc15": [() => import(/* webpackChunkName: "a864fc15" */ "@site/docs/overview/why-crosscall.md"), "@site/docs/overview/why-crosscall.md", require.resolveWeak("@site/docs/overview/why-crosscall.md")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aa7215b9": [() => import(/* webpackChunkName: "aa7215b9" */ "@site/docs/protocol/solvers.md"), "@site/docs/protocol/solvers.md", require.resolveWeak("@site/docs/protocol/solvers.md")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "b7232495": [() => import(/* webpackChunkName: "b7232495" */ "@site/docs/use-cases/native-execution.md"), "@site/docs/use-cases/native-execution.md", require.resolveWeak("@site/docs/use-cases/native-execution.md")],
  "c377a04b": [() => import(/* webpackChunkName: "c377a04b" */ "@site/docs/index.md"), "@site/docs/index.md", require.resolveWeak("@site/docs/index.md")],
  "d72ac48e": [() => import(/* webpackChunkName: "d72ac48e" */ "@site/docs/overview/architecture.md"), "@site/docs/overview/architecture.md", require.resolveWeak("@site/docs/overview/architecture.md")],
  "ea5f5a5c": [() => import(/* webpackChunkName: "ea5f5a5c" */ "@site/docs/use-cases/overview.md"), "@site/docs/use-cases/overview.md", require.resolveWeak("@site/docs/use-cases/overview.md")],};
